import test from 'node:test';
import assert from 'node:assert/strict';
import { createSession } from '../src/analytics/session.js';
function fixture(){let time=1000;const writes=[];return {tick:ms=>time+=ms,writes,session:createSession({id:crypto.randomUUID(),now:()=>time,write:async snapshot=>writes.push(snapshot)})};}
test('active duration excludes an hour in a hidden tab',()=>{const {session,tick}=fixture();tick(10000);session.visibility(false);tick(3600000);session.visibility(true);tick(5000);assert.equal(session.snapshot().activeSeconds,15);});
test('scroll updates stay in memory until one summarized flush',async()=>{const {session,writes}=fixture();await session.flush();for(let i=0;i<1000;i++)session.scroll(i%101);assert.equal(writes.length,1);assert.equal(session.snapshot().maxScrollPercent,100);await session.flush();assert.equal(writes.length,2);});
test('milestones are allowlisted and deduplicated',()=>{const {session}=fixture();assert.equal(session.event('section_reached','brief'),true);assert.equal(session.event('section_reached','brief'),false);assert.equal(session.event('section_reached','arbitrary'),false);assert.equal(session.event('constructor'),false);assert.equal(session.event('ip_address','127.0.0.1'),false);session.event('love_letter_opened');for(let i=1;i<=5;i++)session.event('heart_found',`heart-${i}`);session.event('heart_found','heart-1');const row=session.snapshot();assert.equal(row.loveLetterReached,true);assert.equal(row.loveLetterOpened,true);assert.equal(row.heartsDiscovered,5);assert.equal(row.allHeartsFound,true);assert.equal(row.events.filter(e=>e.name==='heart_found').length,5);});
test('preview exclusion is saved and stopped sessions no longer write',async()=>{const {session,writes}=fixture();await session.flush();session.exclude();await session.flush();assert.equal(writes.at(-1).excluded,true);session.stop();await session.flush();assert.equal(writes.length,2);});
test('session IDs are fresh and failed writes are not marked as saved',async()=>{const {session}=fixture();const other=fixture().session;assert.notEqual(session.snapshot().sessionId,other.snapshot().sessionId);const failing=createSession({id:crypto.randomUUID(),write:async()=>{throw new Error('offline');}});await assert.rejects(failing.flush());assert.equal(failing.dirty,true);});
test('one dominant section accrues time; hidden time and unopened letter do not count as letter reading',()=>{const {session,tick}=fixture();session.section('liebe');tick(12000);session.section('brief');tick(3000);session.event('love_letter_opened');tick(8000);session.visibility(false);tick(3600000);session.visibility(true);tick(2000);session.event('love_letter_closed');tick(1000);session.section('finale');const row=session.snapshot();assert.equal(row.activeSeconds,26);assert.equal(row.sectionActiveSeconds.liebe,12);assert.equal(row.sectionActiveSeconds.brief,14);assert.equal(row.loveLetterActiveSeconds,10);assert.ok(row.events.some(e=>e.name==='section_left'&&e.value==='brief'));assert.ok(row.events.some(e=>e.name==='love_letter_closed'));});
test('interaction IDs are allowlisted, preview stop freezes counters, events remain bounded',()=>{const {session,tick}=fixture();session.event('love_reason_opened','12');session.event('love_reason_opened','13');session.event('open_when_opened','6:7');session.event('open_when_opened','7:8');for(let i=0;i<400;i++){session.section(i%2?'brief':'liebe');tick(10);}session.progress(55.9);session.progress(12);const row=session.snapshot();assert.deepEqual(row.loveReasonsOpened,['12']);assert.deepEqual(row.openWhenOpened,['6:7']);assert.equal(row.mapProgressPercent,55);assert.equal(row.events.length,256);session.stop();session.section('finale');session.progress(100);tick(10000);assert.equal(session.snapshot().mapProgressPercent,55);assert.equal(session.snapshot().activeSeconds,row.activeSeconds);});
test('withdrawal waits for an already pending write before deletion can run',async()=>{let finish;const saved=[];const session=createSession({id:crypto.randomUUID(),write:async row=>{await new Promise(resolve=>{finish=resolve;});saved.push(row);}});const flushing=session.flush();await Promise.resolve();session.stop();let settled=false;const waiting=session.settled().then(()=>{settled=true;});await Promise.resolve();assert.equal(settled,false);finish();await flushing;await waiting;assert.equal(saved.length,1);await session.flush();assert.equal(saved.length,1);});
