import { useEffect, useRef, useState } from 'react';
import { motion, useScroll, useTransform, useReducedMotion } from 'framer-motion';
import { Reveal, Section, Modal, readStore, writeStore } from './Shared';
import { useDiscovery } from './Discoveries';
import { useExperienceSound } from './ExperienceSound';
import { memories, observations, changelog } from '../data/personal';

function Quiet({children}){return <Reveal className="personal-pause"><p>{children}</p></Reveal>;}
export function HennaMotif({small=false}){
 const reduced=useReducedMotion();
 return <svg className={small?'henna-line henna-line--small':'henna-line'} viewBox="0 0 400 160" aria-hidden="true"><motion.path d="M20 120C60 115 70 30 120 42S155 138 200 98S230 20 268 50S265 130 320 105Q350 90 380 50M120 42Q92 75 115 95M200 98Q170 62 190 40M268 50Q310 30 322 60" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" initial={reduced?false:{pathLength:0}} whileInView={{pathLength:1}} viewport={{once:true,amount:.5}} transition={{duration:3}}/></svg>;
}
export function MemoryExchange(){
 const [missing,setMissing]=useState(false);
 return <Section id="mitgegeben" number="MEMORY / 01" title="Was bleibt" className="personal-chapter">
  <Quiet>Manchmal bleiben Dinge zurück.</Quiet><Quiet>Und manchmal gibt man etwas absichtlich mit.</Quiet>
  <Reveal className="exchange-object"><svg viewBox="0 0 180 180" aria-hidden="true"><path d="M55 50C20 10 15 75 43 75C30 130 45 160 90 160S150 130 137 75C170 75 155 10 125 50C100 30 80 30 55 50Z"/><circle cx="70" cy="75" r="3"/><circle cx="110" cy="75" r="3"/><path d="M80 95Q90 105 100 95"/></svg><p className="eyebrow">Eine Woche ohne mein Kuscheltier.</p><h2>Ich hab es dir mitgegeben.</h2><p className="subtle">Nicht, weil ich es vergessen hatte. Für ungefähr eine Woche war etwas von mir bei dir.</p></Reveal>
  <Quiet>Und dafür ist etwas von dir bei mir geblieben.</Quiet>
  <Reveal className="exchange-object"><svg viewBox="0 0 180 180" aria-hidden="true"><path d="M55 20H125L140 155H100L90 70L80 155H40Z M55 38H125"/></svg><p className="eyebrow">Deine Hose.</p><h2>Die immer noch hier liegt.</h2><p className="subtle">Die du bei mir vergessen hast. Und die irgendwie immer noch nach dir riecht.</p><button className="memory-code" aria-expanded={missing} onClick={()=>setMissing(!missing)}>missing_items: 1</button>{missing&&<p className="tiny">Yaels Hose · immer noch bei Kiron · Rückgabe: irgendwann</p>}</Reveal>
  <Reveal className="exchange-end"><div className="exchange-names"><span>KIRON<small>Deine Hose bei mir</small></span><span aria-hidden="true">↔</span><span>YAEL<small>Mein Kuscheltier bei dir</small></span></div><h2>Etwas von mir bei dir.<br/>Etwas von dir bei mir.</h2></Reveal>
 </Section>;
}
export function HennaMemory(){return <Section id="henna" number="MEMORY / 02" title="Eine Spur" className="personal-chapter"><Reveal><p className="eyebrow">Eigentlich nur Henna.</p><HennaMotif/><h2>Das hast du mir gemalt.</h2><p className="subtle">Für mich inzwischen eine Erinnerung, die man anfassen konnte.</p></Reveal></Section>;}
function TrainVisit({second=false}){
 const reduced=useReducedMotion();
 return <div className="train-visit"><Reveal><p className="eyebrow">Besuch {second?'02':'01'}</p><h3>{second?'Dieses Mal wussten wir es besser.':'Zusammen auf deinen Zug gewartet.'}</h3>{second&&<p className="subtle">Dachten wir.</p>}<div className="departure-board"><span>HEIMFAHRT</span><span>KREFELD</span><small>Am Bahnsteig: Kiron & Yael</small></div></Reveal><div className="train-track" aria-hidden="true"><motion.div className="memory-train" initial={reduced?false:{x:0}} whileInView={{x:reduced?0:'-110%'}} viewport={{once:true,amount:.8}} transition={{duration:2,delay:.7,ease:'easeInOut'}}><i/><i/><i/><i/></motion.div></div><Reveal className="train-punchline"><p className="eyebrow">Falsche Richtung.</p><p>{second?'Schon wieder.':'Okay. Kann passieren.'}</p></Reveal></div>;
}
export function TrainMemory(){return <Section id="zuege" number="MEMORY / 03" title="Zwei Heimfahrten" className="personal-chapter"><Quiet>Und dann wären da noch deine Züge.</Quiet><TrainVisit/><TrainVisit second/><Quiet>Zweimal bei mir gewesen.<br/>Zweimal zusammen auf deinen Zug gewartet.<br/>Zweimal falsch gefahren.</Quiet><Reveal><h2>Wenigstens hast du den Weg zu mir gefunden.</h2><p className="tiny train-callback">KREFELD · hoffentlich diesmal die richtige Richtung</p></Reveal></Section>;}
export function YaelArchive(){return <Section id="yael-archive" number="PRIVATE COLLECTION" title="The Yael Archive" className="personal-chapter"><Reveal><h2>The Yael Archive</h2><p className="subtle">Kleine Dinge, die ich nicht vergessen will.</p></Reveal><div className="memory-archive">{memories.map(([title,text],i)=><details key={title}><summary><span className="archive-number">ARCHIVE #{String(i+1).padStart(3,'0')}</span><span>{title}</span><span aria-hidden="true">+</span></summary><p>{text}</p></details>)}</div></Section>;}
export function IPayAttention(){const [index,setIndex]=useState(0);return <Section id="aufmerksam" number="A LITTLE NOTE" title="Was ich mir merke" className="personal-chapter"><Reveal><p className="eyebrow">I PAY ATTENTION.</p><h2>Vielleicht mehr,<br/>als du denkst.</h2></Reveal><div className="attention-note" aria-live="polite"><p className="eyebrow">{String(index+1).padStart(2,'0')} / {observations.length}</p><h3>{observations[index][0]}</h3><p className="subtle">{observations[index][1]}</p></div><div className="attention-controls"><button onClick={()=>setIndex((index+observations.length-1)%observations.length)} aria-label="Vorige Beobachtung">←</button><button onClick={()=>setIndex((index+1)%observations.length)} aria-label="Nächste Beobachtung">Noch eine Kleinigkeit →</button></div></Section>;}
export function ProjectHours(){
 const ref=useRef(null),reduced=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const scale=useTransform(scrollYProgress,[0,.5,1],[.94,1,.98]);
 return <section id="projektzeit" className="project-hours personal-chapter" ref={ref}><div className="section-inner"><Quiet>Du wirst dich vielleicht irgendwann fragen,<br/>wie lange ich daran saß.</Quiet><Quiet>Ich hab irgendwann aufgehört zu zählen.</Quiet><motion.div style={reduced?{}:{scale}} className="hours-numbers">{[['580+','STUNDEN'],['34.800+','MINUTEN'],['2.088.000+','SEKUNDEN']].map(([value,label])=><Reveal key={label}><strong>{value}</strong><p className="eyebrow">{label}</p></Reveal>)}</motion.div><Quiet>Nicht weil eine Website 580 Stunden braucht.</Quiet><Quiet>Sondern weil deine immer noch nicht fertig genug war.</Quiet><Reveal><h2>Und ich würde jede einzelne Stunde nochmal investieren.</h2><p className="subtle">For you.</p></Reveal></div></section>;
}
export function FinalCredits(){
 const {found,discover}=useDiscovery();const play=useExperienceSound();const [project,setProject]=useState(false),[version,setVersion]=useState(false);const done=useRef(false);
 useEffect(()=>{if(found.includes('post-finale'))writeStore('yael-completed',true);},[found]);
 function openProject(){discover('project-yael');writeStore('yael-project-discovered',true);setProject(true);play('project');}
 return <section id="credits" className="final-credits personal-chapter"><HennaMotif small/><Reveal><p className="eyebrow">PROJECT YAEL</p><div className="credits-lines">{['Designed','Written','Developed','Tested','Overthought','Rebuilt way too many times'].map(x=><p key={x}>{x} by Kiron</p>)}</div></Reveal><Reveal><h2>Made for Yael.</h2><p className="fine-date">09.04.2026 — ∞</p></Reveal><div className="credits-discoveries"><button className="memory-code" aria-label="Eine kleine Projektspur öffnen" onClick={openProject}>{found.includes('project-yael')?'project_yael: discovered':'{/* für dich */}'}</button><button className="memory-code" onClick={()=>{setVersion(true);if(!done.current){play('finale');done.current=true;}}} aria-expanded={version}>v1.0</button>{version&&<Reveal><p className="tiny">There will never be a final version.</p></Reveal>}</div>{project&&<Modal title="PROJECT YAEL / DEVELOPMENT ARCHIVE" onClose={()=>setProject(false)}><dl className="project-facts">{[['PROJECT','YAEL'],['RELEASE','14 OCT 2026'],['DEVELOPMENT TIME','580+ HOURS'],['STATUS','NEVER REALLY FINISHED']].map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><p className="tiny">Ein liebevoll überspitztes Entwicklungsprotokoll — keine echten Versions- oder Git-Statistiken.</p><ol className="project-log">{changelog.map(([v,text])=><li key={v}><span>{v}</span><p>„{text}“</p><div className="iteration-bars" aria-hidden="true"><i/><i/><i/></div></li>)}</ol></Modal>}</section>;
}
export function ReturnMemory(){
 const initialized=useRef(false);const [greeting,setGreeting]=useState('');
 useEffect(()=>{if(initialized.current)return;initialized.current=true;const old=readStore('yael-experience-memory',{});const count=Number.isSafeInteger(old.visitCount)?old.visitCount:0;writeStore('yael-experience-memory',{hasVisited:true,visitCount:Math.min(count+1,100000)});if(count===1)setGreeting('Du bist wieder da. ♡');else if(count===4)setGreeting('Dein kleines Stück von uns ist noch hier. ♡');},[]);
 return greeting?<p className="return-memory">{greeting}</p>:null;
}
